- name: Download Toolchain
        run: |
          TOOLCHAIN_DIR="$HOME/toolchains/neutron-clang"
          mkdir -p "$TOOLCHAIN_DIR"
          cd "$TOOLCHAIN_DIR"
          curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
          chmod +x antman
          ./antman -S
          echo "Toolchain files:"
          ls -lR "$TOOLCHAIN_DIR"
