name: Kernel Build(neutron)

on:
  workflow_dispatch:

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4.2.2

      - name: Install Build Dependencies
        run: |
            sudo apt install -y \
            git ccache build-essential bc bison flex libssl-dev libncurses-dev \
            liblz4-tool libzstd-dev zstd curl python3 unzip aria2 device-tree-compiler

      - name: Download Toolchain
        run: |
          TOOLCHAIN_DIR="$HOME/toolchains/neutron-clang"
          mkdir -p "$TOOLCHAIN_DIR"
          cd "$TOOLCHAIN_DIR"
          curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
          chmod +x antman
          ./antman -S

      - name: Upload Toolchain Artifact
        uses: actions/upload-artifact@v4
        with:
          name: neutron-toolchain
          path: $HOME/toolchains/neutron-clang
       
